services:
  - type: web
    name: wedding-site
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: "Wedding Site"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:JyDOXUOhOJODtlEs98QAgvYKDgwgihgNq6kR20hi3L4=
      - key: APP_URL
        value: https://wedding-site.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: ep-gentle-flower-anxlge3z-pooler.c-6.us-east-1.aws.neon.tech
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: neondb
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_AsiqvGK1EN9f
      - key: DB_SSLMODE
        value: require
      - key: CACHE_DRIVER
        value: database
      - key: SESSION_DRIVER
        value: database
      - key: FILESYSTEM_DISK
        value: cloudinary
      - key: CLOUDINARY_URL
        value: cloudinary://436768251945478:6pSBqtIUF51m4p4qENqIHKpBzAE@dw7xj0bq0
      - key: CLOUDINARY_CLOUD_NAME
        value: dw7xj0bq0
      - key: CLOUDINARY_API_KEY
        value: 436768251945478
      - key: CLOUDINARY_API_SECRET
        value: 6pSBqtIUF51m4p4qENqIHKpBzAE
